from abc import ABC, abstractmethod
from typing import Any, Dict, Optional
from pydantic import BaseModel, Field


class MetricResult(BaseModel):
    """Normalized output schema for all evaluators in the VeriFA AI platform."""
    metric_type: str = Field(..., description="Unique machine-readable metric key, e.g. 'hallucination'")
    label: str = Field(..., description="Human-readable title, e.g. 'Hallucination & Factual Consistency'")
    status: str = Field(
        ...,
        description="'evaluated' for active real models, 'coming_soon' for roadmapped metrics, 'skipped' or 'error'"
    )
    raw_score: Optional[float] = Field(
        default=None,
        description="The unadulterated score emitted by the underlying model or measurement"
    )
    normalized_score: Optional[float] = Field(
        default=None,
        description="Score scaled between 0.0 (worst) and 1.0 (best) if applicable"
    )
    risk_level: str = Field(
        default="unknown",
        description="Application-level risk classification: 'low', 'medium', 'high', or 'unknown'"
    )
    details: Dict[str, Any] = Field(
        default_factory=dict,
        description="Auxiliary details (model info, tokens, confidence breakdown, etc.)"
    )
    error_message: Optional[str] = Field(
        default=None,
        description="Descriptive error explanation if evaluation failed"
    )


class BaseEvaluator(ABC):
    """Abstract Base Class for all VeriFA AI evaluators.

    Ensures decoupling of the evaluation engine from the API transport layer.
    """

    @property
    @abstractmethod
    def metric_name(self) -> str:
        """The identifier for this evaluator (e.g. 'hallucination')."""
        pass

    @property
    @abstractmethod
    def display_label(self) -> str:
        """User-friendly name for reporting and UI."""
        pass

    @property
    def is_implemented(self) -> bool:
        """Whether this evaluator uses an active ML model or is a roadmapped stub."""
        return True

    @abstractmethod
    async def evaluate(
        self,
        prompt: str,
        chatbot_response: str,
        reference_evidence: Optional[str] = None,
        **kwargs
    ) -> MetricResult:
        """Executes the evaluation.

        Args:
            prompt: The user prompt sent to the external chatbot.
            chatbot_response: The text generated by the external chatbot.
            reference_evidence: Optional ground-truth, reference context, or document evidence.

        Returns:
            MetricResult with raw and interpreted metrics.
        """
        pass
