import csv
from datetime import datetime, timezone
import html
import io
import json
import logging
from typing import Any, Dict, List, Optional

def _safe_xml(val: Any, limit: Optional[int] = None) -> str:
    """Safely escapes strings for ReportLab XML/HTML Paragraph elements."""
    if val is None:
        return ""
    s = str(val)
    if limit and len(s) > limit:
        s = s[:limit] + "..."
    return html.escape(s)

import reportlab
import reportlab.pdfgen.canvas
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    KeepTogether,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.graphics.shapes import Drawing, Rect, String, Group

logger = logging.getLogger("verifa.services.testlab_report")

# VeriFA brand palette
COLOR_PRIMARY_DARK = colors.HexColor("#0B0F17")
COLOR_CARD_DARK = colors.HexColor("#121824")
COLOR_BORDER = colors.HexColor("#2A3447")
COLOR_GOLD = colors.HexColor("#E5A93C")
COLOR_CYAN = colors.HexColor("#00C2D1")
COLOR_EMERALD = colors.HexColor("#10B981")
COLOR_RED = colors.HexColor("#EF4444")
COLOR_TEXT_MAIN = colors.HexColor("#1E293B")
COLOR_TEXT_MUTED = colors.HexColor("#64748B")
COLOR_LIGHT_BG = colors.HexColor("#F8FAFC")
COLOR_HEADER_BG = colors.HexColor("#0F172A")


class NumberedCanvas(reportlab.pdfgen.canvas.Canvas):
    """Custom canvas that adds page numbers in a two-pass render."""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count: int):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(COLOR_TEXT_MUTED)

        # Header (Pages > 1)
        if self._pageNumber > 1:
            self.drawString(54, 750, "VeriFa-AI • TestLab Automated Benchmark Report")
            self.setStrokeColor(colors.HexColor("#E2E8F0"))
            self.setLineWidth(0.5)
            self.line(54, 742, 558, 742)

        # Footer (All pages)
        self.setStrokeColor(colors.HexColor("#E2E8F0"))
        self.setLineWidth(0.5)
        self.line(54, 45, 558, 45)

        footer_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 32, footer_text)
        self.drawString(54, 32, "Confidential • Generated by VeriFa-AI Platform")
        self.restoreState()


class TestLabReportGenerator:
    """Generates professional PDF, CSV, and JSON evaluation reports for TestLab runs."""

    @classmethod
    def generate_pdf(cls, run_dict: Dict[str, Any]) -> bytes:
        """Renders complete multi-page PDF evaluation report using ReportLab."""
        buffer = io.BytesIO()
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            leftMargin=54,
            rightMargin=54,
            topMargin=54,
            bottomMargin=54
        )

        styles = getSampleStyleSheet()

        # Custom typography styles
        title_style = ParagraphStyle(
            "CoverTitle",
            parent=styles["Normal"],
            fontName="Helvetica-Bold",
            fontSize=26,
            leading=32,
            textColor=COLOR_HEADER_BG,
            spaceAfter=6
        )
        subtitle_style = ParagraphStyle(
            "CoverSubtitle",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=13,
            leading=18,
            textColor=COLOR_GOLD,
            spaceAfter=15
        )
        h1_style = ParagraphStyle(
            "Heading1_Custom",
            parent=styles["Heading1"],
            fontName="Helvetica-Bold",
            fontSize=15,
            leading=20,
            textColor=COLOR_HEADER_BG,
            spaceBefore=14,
            spaceAfter=8,
            keepWithNext=True
        )
        body_style = ParagraphStyle(
            "Body_Custom",
            parent=styles["Normal"],
            fontName="Helvetica",
            fontSize=9.5,
            leading=14,
            textColor=COLOR_TEXT_MAIN
        )
        code_style = ParagraphStyle(
            "Code_Custom",
            parent=styles["Normal"],
            fontName="Courier",
            fontSize=8,
            leading=11,
            textColor=COLOR_HEADER_BG
        )

        elements = []

        # ----------------------------------------------------
        # 1. COVER / HEADER SECTION
        # ----------------------------------------------------
        elements.append(Paragraph("VeriFa-AI", subtitle_style))
        elements.append(Paragraph("TestLab Evaluation Report", title_style))
        elements.append(HRFlowable(width="100%", thickness=2, color=COLOR_GOLD, spaceBefore=4, spaceAfter=15))

        # Metadata Box
        date_str = run_dict.get("created_at", "")
        if date_str:
            try:
                dt = datetime.fromisoformat(date_str.replace("Z", "+00:00"))
                formatted_date = dt.strftime("%B %d, %Y at %H:%M UTC")
            except Exception:
                formatted_date = str(date_str)
        else:
            formatted_date = datetime.now(timezone.utc).strftime("%B %d, %Y")

        meta_data = [
            [
                Paragraph("<b>Chatbot Under Test:</b>", body_style),
                Paragraph(_safe_xml(run_dict.get("chatbot_name", "Unknown"), 40), body_style),
                Paragraph("<b>Evaluation Date:</b>", body_style),
                Paragraph(_safe_xml(formatted_date), body_style),
            ],
            [
                Paragraph("<b>Test Run ID:</b>", body_style),
                Paragraph(_safe_xml(str(run_dict.get("id", ""))[:18] + "..."), code_style),
                Paragraph("<b>Benchmark Suite:</b>", body_style),
                Paragraph(_safe_xml(str(run_dict.get("test_suite", "full")).upper()), body_style),
            ],
            [
                Paragraph("<b>Endpoint Tested:</b>", body_style),
                Paragraph(_safe_xml(str(run_dict.get("api_endpoint", "Configured API"))[:35] + "..."), code_style),
                Paragraph("<b>Run Status:</b>", body_style),
                Paragraph(f"<b>{_safe_xml(run_dict.get('status', 'Completed'))}</b>", body_style),
            ]
        ]
        meta_table = Table(meta_data, colWidths=[110, 150, 100, 144])
        meta_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), COLOR_LIGHT_BG),
            ("BOX", (0, 0), (-1, -1), 0.75, COLOR_BORDER),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E2E8F0")),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ]))
        elements.append(meta_table)
        elements.append(Spacer(1, 15))

        # ----------------------------------------------------
        # 2. EXECUTIVE SUMMARY
        # ----------------------------------------------------
        elements.append(Paragraph("Executive Summary", h1_style))

        total_tests = run_dict.get("total_tests") or run_dict.get("completed_tests") or 0
        passed = run_dict.get("passed_tests", 0)
        issues = run_dict.get("potential_issue_tests", 0)
        errors = run_dict.get("failed_tests", 0)
        duration = run_dict.get("duration_seconds", 0.0)

        exec_summary_data = [
            ["Total Tests", "Passed", "Potential Issues", "Execution Errors", "Duration"],
            [
                str(total_tests),
                f"{passed} ({round(passed/total_tests*100, 1) if total_tests else 0}%)",
                f"{issues} ({round(issues/total_tests*100, 1) if total_tests else 0}%)",
                str(errors),
                f"{duration}s"
            ]
        ]
        exec_table = Table(exec_summary_data, colWidths=[95, 110, 115, 105, 79])
        exec_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), COLOR_HEADER_BG),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, 0), 9),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
            ("BACKGROUND", (0, 1), (-1, 1), colors.white),
            ("FONTNAME", (0, 1), (-1, 1), "Helvetica-Bold"),
            ("FONTSIZE", (0, 1), (-1, 1), 11),
            ("TEXTCOLOR", (1, 1), (1, 1), COLOR_EMERALD),
            ("TEXTCOLOR", (2, 1), (2, 1), colors.HexColor("#D97706")),
            ("TEXTCOLOR", (3, 1), (3, 1), COLOR_RED),
            ("GRID", (0, 0), (-1, -1), 0.5, COLOR_BORDER),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]))
        elements.append(exec_table)
        elements.append(Spacer(1, 15))

        # ----------------------------------------------------
        # 3. EVALUATION METRICS
        # ----------------------------------------------------
        elements.append(Paragraph("Core Evaluation Metrics", h1_style))

        metrics = run_dict.get("summary_metrics", {})
        hl_rate = metrics.get("potential_hallucination_rate", 0.0)
        tox_rate = metrics.get("toxicity_rate", 0.0)
        cons_score = metrics.get("consistency_score", 100.0)
        if_score = metrics.get("instruction_following_score", 100.0)

        metrics_grid = [
            [
                Paragraph("<b>Potential Hallucination Rate:</b>", body_style),
                Paragraph(f"<b>{hl_rate}%</b> (Vectara HHEM)", body_style),
                Paragraph("<b>Toxicity Rate:</b>", body_style),
                Paragraph(f"<b>{tox_rate}%</b>", body_style)
            ],
            [
                Paragraph("<b>Consistency Score:</b>", body_style),
                Paragraph(f"<b>{cons_score}%</b> (Pairwise)", body_style),
                Paragraph("<b>Instruction Following:</b>", body_style),
                Paragraph(f"<b>{if_score}%</b>", body_style)
            ]
        ]
        metrics_table = Table(metrics_grid, colWidths=[140, 112, 140, 112])
        metrics_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F1F5F9")),
            ("BOX", (0, 0), (-1, -1), 0.5, COLOR_BORDER),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CBD5E1")),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ]))
        elements.append(metrics_table)
        elements.append(Spacer(1, 12))

        # ----------------------------------------------------
        # 4. CHARTS: CATEGORY ANALYTICS VISUALIZER
        # ----------------------------------------------------
        elements.append(Paragraph("Category Performance Analytics", h1_style))

        cat_stats = metrics.get("category_analytics", {})
        chart_rows = [["Category", "Total", "Passed", "Issues", "Pass Rate %", "Visual Bar"]]

        for cat_name, data in cat_stats.items():
            if data.get("total", 0) > 0:
                p_rate = data.get("pass_rate", 0.0)
                # Render mini horizontal bar chart using ReportLab Drawing
                d = Drawing(120, 12)
                # Background grey bar
                d.add(Rect(0, 2, 110, 8, fillColor=colors.HexColor("#E2E8F0"), strokeColor=None))
                # Filled pass bar
                fill_width = min(110, max(0, int(110 * (p_rate / 100.0))))
                d.add(Rect(0, 2, fill_width, 8, fillColor=COLOR_EMERALD, strokeColor=None))

                chart_rows.append([
                    cat_name,
                    str(data.get("total", 0)),
                    str(data.get("passed", 0)),
                    str(data.get("issues", 0)),
                    f"{p_rate}%",
                    d
                ])

        if len(chart_rows) > 1:
            chart_table = Table(chart_rows, colWidths=[130, 45, 50, 50, 75, 154])
            chart_table.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#334155")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 8.5),
                ("GRID", (0, 0), (-1, -1), 0.5, COLOR_BORDER),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING", (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]))
            elements.append(chart_table)
        else:
            elements.append(Paragraph("Category breakdown analytics recorded in run summary.", body_style))

        elements.append(Spacer(1, 15))

        # ----------------------------------------------------
        # 5. DETAILED FINDINGS & TEST EVIDENCE
        # ----------------------------------------------------
        results_list = run_dict.get("results", [])
        flagged_cases = [r for r in results_list if r.get("status") in ("POTENTIAL ISSUE", "EXECUTION ERROR")]

        elements.append(Paragraph(f"Detailed Findings & Test Evidence ({len(flagged_cases)} Flagged)", h1_style))
        elements.append(Paragraph(
            "The following test cases exhibited potential hallucinations, instruction violations, or execution faults:",
            body_style
        ))
        elements.append(Spacer(1, 8))

        if not flagged_cases:
            elements.append(Paragraph("<b>No potential issues or errors were detected during this benchmark run.</b>", body_style))
        else:
            # Show up to 15 key findings with full evidence
            for idx, case in enumerate(flagged_cases[:15], start=1):
                case_elements = []
                c_id = case.get("test_id", "")
                cat = case.get("category", "")
                c_status = case.get("status", "")
                c_sev = str(case.get("severity", "medium")).upper()
                c_score = case.get("score")
                c_thresh = case.get("threshold")

                score_info = f"Score: {c_score} | Threshold: {c_thresh}" if c_score is not None else "Score: N/A"

                finding_header = f"<b>#{_safe_xml(c_id)} • {_safe_xml(cat)}</b> [Status: {_safe_xml(c_status)} | Severity: {_safe_xml(c_sev)} | {_safe_xml(score_info)}]"
                case_elements.append(Paragraph(finding_header, ParagraphStyle("FindingH", fontName="Helvetica-Bold", fontSize=9, textColor=COLOR_HEADER_BG)))

                p_prompt = Paragraph(f"<b>Prompt:</b> {_safe_xml(case.get('prompt', ''), 250)}", body_style)
                p_resp = Paragraph(f"<b>Chatbot Response:</b> {_safe_xml(case.get('chatbot_response', '(Empty)'), 300)}", code_style)
                p_ref = Paragraph(f"<b>Reference Information:</b> {_safe_xml(case.get('reference_information', '(None)'), 250)}", body_style)
                p_reason = Paragraph(f"<b>Evaluation Reason:</b> {_safe_xml(case.get('reason', ''))}", body_style)

                evidence_data = [[p_prompt], [p_resp], [p_ref], [p_reason]]
                evidence_table = Table(evidence_data, colWidths=[490])
                evidence_table.setStyle(TableStyle([
                    ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#F8FAFC")),
                    ("BOX", (0, 0), (-1, -1), 0.5, COLOR_BORDER),
                    ("TOPPADDING", (0, 0), (-1, -1), 3),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                    ("LEFTPADDING", (0, 0), (-1, -1), 6),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 6),
                ]))
                case_elements.append(evidence_table)
                case_elements.append(Spacer(1, 8))

                elements.append(KeepTogether(case_elements))

        elements.append(Spacer(1, 10))

        # ----------------------------------------------------
        # 6. CONCLUSION (Factual, grounded, non-absolute claims)
        # ----------------------------------------------------
        elements.append(Paragraph("Conclusion", h1_style))
        conclusion_text = (
            f"The automated TestLab benchmark run for <b>{_safe_xml(run_dict.get('chatbot_name', 'the target chatbot'), 50)}</b> "
            f"executed a total of <b>{total_tests}</b> test cases across 8 standardized evaluation categories. "
            f"The evaluation identified <b>{issues}</b> potential issue cases ({hl_rate}% potential hallucination rate) "
            f"and <b>{errors}</b> execution error(s). "
            f"A total of <b>{passed}</b> tests fully satisfied the automated evaluation criteria. "
            f"These findings reflect the empirical performance of the chatbot on the predefined test prompts at the time of testing."
        )
        elements.append(Paragraph(conclusion_text, body_style))
        elements.append(Spacer(1, 12))

        # ----------------------------------------------------
        # 7. DISCLAIMER (Strict requirement)
        # ----------------------------------------------------
        disclaimer_text = (
            "<b>Disclaimer:</b> Automated evaluation results are indicative and should be reviewed by humans "
            "for important or high-risk use cases. No automated evaluation proves complete safety or absence of error."
        )
        disc_table = Table([[Paragraph(disclaimer_text, ParagraphStyle("Disc", fontName="Helvetica-Oblique", fontSize=8.5, leading=12, textColor=colors.HexColor("#475569")))]], colWidths=[504])
        disc_table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#FFFBEB")),
            ("BOX", (0, 0), (-1, -1), 1, colors.HexColor("#FDE68A")),
            ("TOPPADDING", (0, 0), (-1, -1), 8),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ("LEFTPADDING", (0, 0), (-1, -1), 10),
            ("RIGHTPADDING", (0, 0), (-1, -1), 10),
        ]))
        elements.append(disc_table)

        # Build document with custom canvas
        doc.build(elements, canvasmaker=NumberedCanvas)
        buffer.seek(0)
        return buffer.getvalue()

    @classmethod
    def generate_csv(cls, run_dict: Dict[str, Any]) -> str:
        """Generates RFC 4180 compliant CSV export containing all executed test results."""
        results = run_dict.get("results", [])
        output = io.StringIO()
        writer = csv.writer(output, quoting=csv.QUOTE_MINIMAL)

        # Mandatory columns requested:
        # test_id, category, prompt, chatbot_response, reference_information, evaluation_result, score, reason, severity
        writer.writerow([
            "test_id",
            "category",
            "prompt",
            "chatbot_response",
            "reference_information",
            "evaluation_result",
            "score",
            "reason",
            "severity",
            "latency_ms",
            "timestamp"
        ])

        for r in results:
            writer.writerow([
                r.get("test_id", ""),
                r.get("category", ""),
                r.get("prompt", ""),
                r.get("chatbot_response", ""),
                r.get("reference_information", ""),
                r.get("status", ""),
                r.get("score") if r.get("score") is not None else "",
                r.get("reason", ""),
                r.get("severity", ""),
                r.get("latency_ms", 0.0),
                r.get("timestamp", "")
            ])

        return output.getvalue()

    @classmethod
    def generate_json(cls, run_dict: Dict[str, Any]) -> Dict[str, Any]:
        """Returns the full structured TestLab report payload."""
        return {
            "report_type": "VeriFa-AI TestLab Evaluation Report",
            "version": "1.0.0",
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "run_metadata": {
                "run_id": run_dict.get("id"),
                "chatbot_name": run_dict.get("chatbot_name"),
                "api_endpoint": run_dict.get("api_endpoint"),
                "test_suite": run_dict.get("test_suite"),
                "status": run_dict.get("status"),
                "total_tests": run_dict.get("total_tests"),
                "completed_tests": run_dict.get("completed_tests"),
                "passed_tests": run_dict.get("passed_tests"),
                "potential_issue_tests": run_dict.get("potential_issue_tests"),
                "failed_tests": run_dict.get("failed_tests"),
                "duration_seconds": run_dict.get("duration_seconds"),
                "start_time": run_dict.get("start_time"),
                "end_time": run_dict.get("end_time")
            },
            "summary_metrics": run_dict.get("summary_metrics", {}),
            "disclaimer": "Automated evaluation results are indicative and should be reviewed by humans for important or high-risk use cases.",
            "test_results": run_dict.get("results", [])
        }
